version: 2.1
orbs:
  node: circleci/node@2.0.2

jobs:
  build:
    docker:
      - image: circleci/node:12.18.4
    steps:
      - checkout
      - run:
          name: update-yarn
          command: 'sudo npm install -g npm@latest'
      - restore_cache:
          key: dependency-cache-{{checksum "yarn.lock"}}
      - run:
          name: install-yarn
          command: yarn install
      - save_cache:
          key: dependency-cache-{{checksum "yarn.lock"}}
          paths:
            - ./node_modules
      - run:
          name: build-dist
          command: yarn build --theme all
  build-minified:
    docker:
      - image: circleci/node:12.18.4
    steps:
      - checkout
      - run:
          name: update-yarn
          command: 'sudo npm install -g npm@latest'
      - restore_cache:
          key: dependency-cache-{{checksum "yarn.lock"}}
      - run:
          name: install-yarn
          command: yarn install
      - save_cache:
          key: dependency-cache-{{checksum "yarn.lock"}}
          paths:
            - ./node_modules
      - run:
          name: build-dist-minfied
          command: yarn build --theme all --minified
  test:
    docker:
      - image: circleci/node:12.18.4
    steps:
      - checkout
      - restore_cache:
          key: dependency-cache-{{checksum "yarn.lock"}}
      - run:
          name: test
          command: yarn test
      - save_cache:
          key: dependency-cache-{{checksum "coverage/lcov.info"}}
          paths:
            - ./coverage

workflows:
  version: 2
  build-and-test:
    jobs:
      - build
      - build-minified
      - test:
          requires:
            - build
            - build-minified